# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-28 08:46
from __future__ import unicode_literals

from django.db import migrations
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='illustration',
            field=mezzanine.core.fields.FileField(default=False, max_length=255, verbose_name='Illustration'),
        ),
        migrations.AlterField(
            model_name='client',
            name='logo',
            field=mezzanine.core.fields.FileField(default=False, max_length=255, verbose_name='Logo'),
        ),
    ]
