# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-29 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0004_auto_20160728_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='campagne',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
