# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-07 11:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0006_campagne_clientkey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='illustration',
        ),
    ]
