# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-17 14:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20150527_1555'),
        ('MAIN', '0007_remove_client_illustration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Page')),
                ('content', mezzanine.core.fields.RichTextField(verbose_name='Content')),
                ('job', models.CharField(max_length=255)),
                ('picture', mezzanine.core.fields.FileField(default=False, max_length=255, verbose_name='Picture')),
                ('level', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('_order',),
            },
            bases=('pages.page', models.Model),
        ),
    ]
