# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-07 08:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20150527_1555'),
        ('MAIN', '0008_worker'),
    ]

    operations = [
        migrations.CreateModel(
            name='FakeBlog',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Page')),
                ('content', mezzanine.core.fields.RichTextField(verbose_name='Content')),
                ('baseline', models.CharField(blank=True, max_length=255, null=True, verbose_name='baseline')),
                ('illustration', mezzanine.core.fields.FileField(default=False, max_length=255, verbose_name='Illustration')),
            ],
            options={
                'ordering': ('_order',),
                'verbose_name': 'FAKE_BLOG',
            },
            bases=('pages.page', models.Model),
        ),
        migrations.CreateModel(
            name='FakeBlogGalery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', mezzanine.core.fields.FileField(blank=True, max_length=255, null=True, verbose_name='Image')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('display_size', models.IntegerField(blank=True, default=6, help_text="taille de l'image. Entrez un nombre pair, entre 2 et 12.", null=True)),
                ('FakeBlog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MAIN.FakeBlog')),
            ],
            options={
                'verbose_name': 'Gallerie FakeBlog',
            },
        ),
    ]
